Update @fepitre's Qubes OS key
QubesOS/qubes-builderv2 pull request #100
Opened 2024-04-03 15:27 UTC by fepitre

2024-04-03 21:35 UTC, marmarek commented
A bunch of tests failed :(

2024-04-08 05:26 UTC, fepitre commented
@marmarek we are good here

2024-04-08 09:46 UTC, marmarek requested changes

2024-04-08 09:46 UTC, marmarek commented on qubesbuilder/plugins/fetch/scripts/verify-file
> +    sq toolbox keyring merge --output "$keyring" "${PUBKEY_FILE[@]}"
This needs to be a bit more flexible - Debian still has the old version (and likely will have for quite some time), so old syntax still need to be supported. I don't see an elegant way of checking but `sq help|grep toolbox` might be enough.

2024-04-09 13:04 UTC, marmarek approved these changes

2024-04-09 13:04 UTC, merged