Set option dispvm to qube setting default_dispvm
QubesOS/qubes-builderv2 pull request #135
Opened 2024-07-17 08:39 UTC by ben-grande

Fixes: https://github.com/QubesOS/qubes-issues/issues/8842

2024-07-24 14:12 UTC, ben-grande commented
Last commit only resolves merge conflicts. Unfortunately Github doesn't state there was a conflict in history to elucidate.

2024-08-08 03:27 UTC, marmarek requested changes
Documentation in README and/or `rpc/policy/50-qubesbuilder.policy` needs to be adjusted too.

2024-08-08 09:45 UTC, ben-grande commented
> Documentation in README and/or `rpc/policy/50-qubesbuilder.policy` needs to be adjusted too.

Policy has been updated. Mentions of `qubes-builder-dvm` will stay as it is the default example.

2024-08-08 23:03 UTC, marmarek approved these changes

2024-08-08 23:21 UTC, merged