Several improvements for logging output and error
QubesOS/qubes-builderv2 pull request #138
Opened 2024-07-22 11:17 UTC by fepitre

2024-07-27 16:17 UTC, marmarek requested changes

2024-07-27 16:17 UTC, marmarek commented
The split between the two commits is a bit weird, for example the change `stderr=subprocess.PIPE` in the first commit deadlocks until fixup in the second commit. Or global `log` in the first commit is removed only in some places, while not really used anymore in others. Maybe simply squash the two commits together?

2024-07-27 17:58 UTC, fepitre commented
> The split between the two commits is a bit weird, for example the change `stderr=subprocess.PIPE` in the first commit deadlocks until fixup in the second commit. Or global `log` in the first commit is removed only in some places, while not really used anymore in others. Maybe simply squash the two commits together?

Yes it deserves a squash of the two commits, it has been too much rework at once.

2024-07-30 23:10 UTC, marmarek approved these changes

2024-07-30 23:10 UTC, merged