Rework import of plugins
QubesOS/qubes-builderv2 pull request #4
Opened 2022-09-15 16:57 UTC by fepitre

2022-09-16 03:50 UTC, marmarek requested changes

2022-09-16 03:50 UTC, marmarek commented on qubesbuilder/helpers.py
> +                module = sys.modules[module_pattern % mod_name]
This won't load plugins from `path`, but from standard python locations, and look for `qubesbuilder.plugin` specifically. In other words: this won't work for plugins outside of the builder repo.

2022-09-16 03:50 UTC, marmarek commented on qubesbuilder/helpers.py
> +    modules = _load_modules(kwargs.get("plugins_dir"))
This should allow multiple directories. But also implicitly include main builder repo, instead of requiring to always specify the path explicitly.

2022-09-16 03:50 UTC, marmarek commented on qubesbuilder/plugins/build_deb/__init__.py
> +    def from_args(cls, stage, components, distributions, **kwargs):
make it keyword-only arguments? (same in other plugins)

2022-09-25 07:35 UTC, fepitre commented
PipelineRetry

2022-09-28 13:32 UTC, marmarek approved these changes

2022-09-28 16:52 UTC, merged