Ubuntu
QubesOS/qubes-builderv2 pull request #43
Opened 2023-04-28 14:45 UTC by fepitre

2023-05-04 13:02 UTC, marmarek requested changes

2023-05-04 17:57 UTC, fepitre commented on qubesbuilder/plugins/chroot_deb/__init__.py
> +            pbuilder_cmd += [f"--extrapackages '{' '.join(additional_packages)}'"]
I'm not sure, I need to check what pbuilder is doing.

2023-05-07 15:42 UTC, marmarek commented
black complains...

2023-05-07 16:02 UTC, marmarek requested changes

2023-05-07 16:02 UTC, marmarek commented on qubesbuilder/plugins/chroot_deb/__init__.py
> +            pbuilder_cmd += [f"--extrapackages '{' '.join(additional_packages)}'"]
This is still an issue.

2023-05-07 19:42 UTC, marmarek approved these changes

2023-05-08 00:09 UTC, merged