Fix Qubes executor bugs
QubesOS/qubes-builderv2 pull request #64
Opened 2023-08-04 16:03 UTC by DemiMarie

This fixes multiple problems with the Qubes executor.

2023-08-05 00:04 UTC, marmarek commented
You broke something (env quoting?), see the failed test, which shows now some unexpected quotes somewhere. But also, I don't think it's going to work in general (see 687897a2f0da7a6fe293da1bd173e6990c9073f1), and seems to be unnecessary as those paths are absolute (so, no need to prepend `--`) and are under full control of the builder (which do not use shell meta-characters in any of them).

And also, both mypy and black complains.

2023-08-09 11:51 UTC, marmarek commented
black still complains about formatting

2023-08-14 22:35 UTC, marmarek commented on tools/generate-container-image.sh
> +        --config-opts chroot_setup_cmd='install dnf dnf-plugins-core qubes-core-agent @buildsys-build'
Furthermore, the reason for including it is bogus - repositories in mock config are configured to use keys shipped by builder itself (see `keys_dir` in mock config).

2023-08-14 22:36 UTC, marmarek commented on qubesbuilder/plugins/chroot_rpm/mock/centos-stream.cfg
> +enabled={use_qubes_repo}
This is unnecessary, mock is called with appropriate `--enablerepo` when necessary already.

2023-08-14 22:37 UTC, marmarek commented
Last two commits looks unnecessary and wrong...

2023-08-14 22:48 UTC, DemiMarie commented
> Last two commits looks unnecessary and wrong...

Dropped.  They may have hidden some other problem, but if I have that problem again I’ll look for a better fix.

2023-09-09 03:23 UTC, marmarek commented
PipelineRetry

2023-09-09 19:06 UTC, DemiMarie commented
PipelineRetryFailed

2023-09-09 21:36 UTC, DemiMarie commented
PipelineRetry

2023-12-18 01:36 UTC, tlaurion commented
@marmarek ?

2023-12-18 02:26 UTC, marmarek commented
> @marmarek ? @DemiMarie ?

Are you waiting for some particular change here to be merged @tlaurion ?

2024-01-06 16:08 UTC, marmarek requested changes

2024-01-06 16:08 UTC, marmarek commented on qubesbuilder/executors/qubes.py
> +                        sed_cmd[0],
maybe make `sed_cmd` a string variable instead of array that has further elements ignored?

2024-01-06 16:08 UTC, marmarek commented on qubesbuilder/plugins/fetch/__init__.py
> +            + ">>"
spaces around or at least before?

2024-01-06 16:08 UTC, marmarek commented on qubesbuilder/plugins/fetch/__init__.py
> +            + ">>"
spaces around or at least before?

2024-01-06 16:08 UTC, marmarek commented on qubesbuilder/plugins/fetch/__init__.py
> +                    + ">>"
spaces around or at least before?

2024-01-06 21:44 UTC, DemiMarie commented on qubesbuilder/executors/qubes.py
> +            f"bash -c 'rm -rf -- {quote(str(self.get_builder_dir()))}/incoming/{quote(src.name)} {quote(str(dst.as_posix()))}/{quote(src.name)}'",
I’m going to switch to helper functions that handle quoting automatically.  It makes the code slightly longer but _much_ easier to understand, especially when multiple layers of quoting are involved.

2024-01-06 22:00 UTC, marmarek commented on qubesbuilder/executors/qubes.py
> +    return " && ".join(map(quote_list, args))
```suggestion
    return " && ".join(map(quote_list, cmd))
```
But also, maybe name it `cmds`?

2024-01-06 22:01 UTC, marmarek commented on qubesbuilder/executors/qubes.py
> +        move_to_destination = build_run_cmd_and_list(
Missing vm argument

2024-01-07 13:03 UTC, marmarek approved these changes

2024-01-07 13:05 UTC, merged

2024-01-07 16:00 UTC, tlaurion commented
> > @marmarek ? @DemiMarie ?
> 
> Are you waiting for some particular change here to be merged @tlaurion ? 

No, just that the builder was not working. Will retry