Rework qubes executor to prepare windows integration
QubesOS/qubes-builderv2 pull request #80
Opened 2023-12-29 11:24 UTC by fepitre

2023-12-29 11:24 UTC, fepitre commented
This will fail until `builder-dvm` has RPC updated.

2024-01-03 23:47 UTC, marmarek requested changes

2024-01-03 23:47 UTC, marmarek commented on rpc/qubesbuilder.FileCopyIn
> +    os.chown("/builder", uid, uid)
```suggestion
    gid = os.getgid()
    os.chown("/builder", uid, gid)
```

2024-01-03 23:49 UTC, marmarek commented
And also, black complains about some style changes (mostly indentation).

2024-01-07 16:30 UTC, marmarek approved these changes

2024-01-07 16:30 UTC, merged